export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
export const RECEIVED_EMPLOYEE = 'RECEIVED_EMPLOYEE';
export const STORE_EMPLOYEE = 'STORE_EMPLOYEE';

export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const RECEIVED_PROJECT = 'RECEIVED_PROJECT';
export const STORE_PROJECT = 'STORE_PROJECT';

export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const FETCH_CONTACT = 'FETCH_CONTACT';
export const RECEIVED_CONTACT = 'RECEIVED_CONTACT';
export const STORE_CONTACT = 'STORE_CONTACT';



export const ADD_BID = 'ADD_BID';
export const DELETE_BID = 'DELETE_BID';
export const EDIT_BID = 'EDIT_BID';
